# Generated by Django 5.1.3 on 2024-11-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_core', '0003_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='end_match',
        ),
        migrations.RemoveField(
            model_name='match',
            name='start_match',
        ),
        migrations.AddField(
            model_name='match',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
