# Generated by Django 5.1.3 on 2024-11-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_core', '0004_remove_match_end_match_remove_match_start_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='end_match',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='start_match',
            field=models.DateTimeField(null=True),
        ),
    ]
