# Generated by Django 5.1.3 on 2024-11-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables_core', '0004_player_friends'),
        ('tables_core', '0005_match_end_match_match_start_match'),
    ]

    operations = [
    ]
