# Generated by Django 5.1.3 on 2024-12-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_core', '0007_remove_match_duration_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/player_picture/'),
        ),
    ]
