# Generated by Django 5.1.3 on 2024-12-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_core', '0009_alter_player_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='player_picture/'),
        ),
    ]
