# Generated by Django 5.1 on 2024-12-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_core', '0012_alter_match_adv_score_alter_match_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_anonymized',
            field=models.BooleanField(default=False),
        ),
    ]
